### ISSUE TITLE
Ammo Not Registering

### ISSUE THREAD

**Issue by Krizfrost** [VORPCORE/vorp_weaponsv2#15]
Trying to populate weapon with ammo and its resulting in serverside error
`[script:vorp_weaponsv] > containsammo (@vorp_weaponsv2/server/server.lua:135)
[script:vorp_weaponsv] > ref (@vorp_weaponsv2/server/server.lua:165)
[script:vorp_weaponsv] > rawQuery (@ghmattimysql/dist/build.js:21706)
[script:vorp_weaponsv] > processTicksAndRejections (node:internal/process/task_queues:96)`

**Comment by zeduncan** [comment]
scripts sql use a column ammo in characters table which doesn't exist

exports.ghmattimysql:execute('SELECT ammo FROM characters WHERE charidentifier = @charidentifier ' , {['charidentifier'] = charidentifier}, function(result)

exports.ghmattimysql:execute("UPDATE characters Set ammo=@ammo  WHERE charidentifier=@charidentifier", Parameters)    

exports.ghmattimysql:execute('SELECT ammo FROM characters WHERE charidentifier = @charidentifier ' , {['charidentifier'] = charidentifier}, function(result)

**Comment by outsider31000** [comment]
Then install the sql.

**Comment by zeduncan** [comment]
yes i did find a version of the inventory scripts which had the sql queries  but have another problem with the callback of adbullets function. Investigation in progress.
