### ISSUE TITLE
Crafting not work

### ISSUE THREAD

**Issue by DerHobbs** [VORPCORE/vorp_weaponsv2#28]
the update doesn't work for me, not even without changes, you can no longer craft or beautify. there is no prompt

**Comment by HonorAlterium** [comment]
same here

**Comment by AndrewR3K** [comment]
Do you have vorp_progressbar installed and ensured?

**Comment by outsider31000** [comment]
i dont think its cause of that  @Mycroft-Studios  made some changes and it stopped working

**Comment by outsider31000** [comment]
use the premade
 @HonorAlterium

**Comment by AndrewR3K** [comment]
> i dont think its cause of that @Mycroft-Studios made some changes and it stopped working

Ahh oops sorry, i didn't look at the repo name. Ignore my comment about vorp_progressbar
