### ISSUE TITLE
Using a scoped gun makes HUD go visible, even though disabled in core.

### ISSUE THREAD

**Issue by Fatguypeeking** [VORPCORE/vorp_weaponsv2#34]
I don't know if this issue is to be posted on core, or here.

Issue:
When you add a scope to a gun (In this case, a rolling block), and you aim with the gun (in scope mode), the HUD will go visible, even though disabled in vorp_core.

Sometimes it'll require you to aim 2-3 times before HUD goes visible, other times just a single time.

**Comment by AndrewR3K** [comment]
Ill look into this asap. If disabled in config, the ui shouldn't show.

By chance do you have a video of this error occurring for you? This may help me speed up replicating the issue on my end.
