### ISSUE TITLE
Error Buying weapons at store

### ISSUE THREAD

**Issue by diogoratomas** [VORPCORE/vorp_weaponsv2#37]
![Captura de ecrã 2024-01-14 180959](https://github.com/VORPCORE/vorp_weaponsv2/assets/43974049/57f31473-3456-4760-89d9-6c0c2c770379)
It says i don't have enough money
Already updated server.lua

**Comment by NikitoGOT** [comment]
im have same error

**Comment by outsider31000** [comment]
use the one from premade for now I need to have a look at this when I find the time

**Comment by kochsteven4** [comment]
Here is the issue 
line 328 if money < itemprice then
need to change to 
if money > itemprice then 


Hope that helps

**Comment by outsider31000** [comment]
fixed
